### ISSUE TITLE
New Branch ?

### ISSUE THREAD

**Issue by Anobium** [gawindx/WinNUT-Client#109]
I want to make some updates but no sure whether to create a new branch.

Changes:

1. Remove online update check by adding new Setting option.  The code needs to be standalone to prevent use of internet.
Therefore, hide the online update option from Toast and Setting Tab.  
2. Add new setting to prevent Win10/11 Toast message
3. Add new setting to issue system command xx seconds after UPS issues 'OB' message, cancelling this operation when 'OL' is issued by UPS.
Therefore, add enabling checkbox, time value variable and file select dialog.

Advice plz

**Comment by Anobium** [comment]
![image](https://user-images.githubusercontent.com/17933379/140886992-fb859191-0c83-4c3e-bd88-36273edbe9b4.png)

New dialog

**Comment by gbakeman** [comment]
Thank you for all of the recent suggestions! I'm currently working on a somewhat major overhaul of underlying code so you might want to hold off until then. It's been taking me awhile to get it done, but hopefully I'll have an update ready soon.

**Comment by Anobium** [comment]
This is a great project - well done.

----

I am willing to help.  The changes are really improvements on the solution.
I have been able to get them done but I was going to do them again in a new release to get my coding better!

But, if you can add these to the refactored code then I will hold off.

----
### Improvements are

1. Issue system commend a time period after 'OB' received. Cancelled by 'OL'.
2. Save and retained screen position.  I would add a option in the setting/misc tab for this.  See below.
3. Reorder Settings/Connection. To be logically correct (no functional change)
4. Setting to stop Toasts on Win10/11
5. Setting to hide Update dialogs including Connection/Update tab
6. For any parameter like Firmware that is NOT supported by the UPS then hide the field in WinNUT form.
7. View log folder.

-----

There are a number of typos.  I am happy to review.  Will have to leave the registry typos as this will break things.




![image](https://user-images.githubusercontent.com/17933379/140977028-3bc1f9f0-3969-47cb-acfc-9dcd2a0834f3.png)

**Comment by gbakeman** [comment]
I don't think I can take much credit, @gawindx has been the leader on this! :)

I'm having tunnel vision right now and feel like I need to get my integration project done first, but once I have a beta/alpha release out then I'd like to start pulling in changes other people have made. Your changes here are very good and I'd like to get to them sooner rather than later. I'll keep you updated and see what the next steps are once a release is out.

**Comment by Anobium** [comment]
> I don't think I can take much credit, @gawindx has been the leader on this! :)
> 
> I'm having tunnel vision right now and feel like I need to get my integration project done first, but once I have a beta/alpha release out then I'd like to start pulling in changes other people have made. Your changes here are very good and I'd like to get to them sooner rather than later. I'll keep you updated and see what the next steps are once a release is out.

What changes are you making?

**Comment by gbakeman** [comment]
Issue #54 is the main issue we're tracking this in - essentially core NUT protocol functionality is being moved into a separate library. You can see my progress on that [here](https://github.com/gbakeman/nut-dot-net), then the branch of WinNUT where I'm integrating it is [here](https://github.com/gbakeman/WinNUT-Client). It's been slow going and I apologize for that, I just hesitate to encourage people to make other changes right now since a lot is probably going to change functionally which might require duplicate work for other enhancements or bug fixes.

**Comment by blackie333** [comment]
Could you please try to support NUT emulator/wrapper(on apsupsd) from Martin Machtl, details here: https://www.reddit.com/r/homelab/comments/ar0h9l/apcupsd_nut_wrapper_script_apcupsd_and_nut_on_the/ ? It allows me to use modbus protocol on USB connection and read LOAD values from my APC SMART UPS.
The connection with WinNut v.2.0 is unstable(reconnection loop) and v2.1 gives me error on start.
It's working fine on RPi server and Synology & Home automation plugins clients. 
The last not working client is WinNut which I like very much. Thank you very much

**Comment by gbakeman** [comment]
@blackie333 If their library emulates NUT protocol then WinNUT should be able to communicate without any additional work. Chances are you're experiencing bugs that other people have reported here and will hopefully be fixed soon.

**Comment by blackie333** [comment]
OK, thank you. When there will be a new branch/test version of WinNUT available I'd be glad to test.
