### ISSUE TITLE
Window Title Not the Same After Open And 'In Focus'

### ISSUE THREAD

**Issue by FileCity** [gawindx/WinNUT-Client#61]
WinNut window title is not the same after being just opened and when selected and in focus.
This is an aesthetic issue.
See the two screens below.

![Capture1](https://user-images.githubusercontent.com/70494005/107424977-5b35a300-6aec-11eb-8b50-437bdc3f1fb2.JPG)
![Capture2](https://user-images.githubusercontent.com/70494005/107424978-5b35a300-6aec-11eb-9d6f-77af6bb64d90.JPG)

Running: v2.0.7710.35866

**Comment by gawindx** [comment]
I think I know where it came from.
And personally I prefer to see "Windows NUT Client" than just "WinNUT".

I'll see to change that.

**Comment by FileCity** [comment]
@gawindx, running latest 2.0.7721 and this cosmetic issue is still present.
Upgrade and clean install tested.
Windows title shows WinNUT and changes itself for Windows NUT Client seconds after.

**Comment by gawindx** [comment]
Yes, the name "WinNUT" is a translatable string and for some reason that I haven't figured out yet, the window is displayed first with the untranslated china, then it is replaced by its translation.
It doesn't happen with the different controls and I don't know why it behaves this way.

I also don't want to replace the name of the Form in the code because it matches the name of the VB file and the corresponding class.
