### ISSUE TITLE
Unable to update from 2.0.4.0

### ISSUE THREAD

**Issue by UltraHKR** [gawindx/WinNUT-Client#67]
Version is not correctly detected and 2.0.4.0 is still unable to download the correct package.

As shown in the image below;
(The app downloads a zero byte msi package...)

![image](https://user-images.githubusercontent.com/49404533/107854048-5b34ec00-6de7-11eb-9f55-9fc358e88469.png)

**Comment by gawindx** [comment]
Yes, the reported version number is incorrect.

This is not in itself an anomaly because I have completely updated the update detection process to a much cleaner solution and with a much lighter code.

What I did not anticipate and that the download link no longer works correctly.

You can download the updated version here:
[WinNUT-2.0.7710](https://github.com/gawindx/WinNUT-Client/releases/download/v2.0.7710/WinNUT-Setup.msi)

**Comment by gawindx** [comment]
The necessary steps have been taken to repair the links in both the stable version and the development version.

As the new update process is based on Github APIs, this kind of inconvenience should no longer occur.

I close the issue.
